const refs = {
  gallery: document.querySelector('.movies__list'),
  searchInput: document.querySelector('.search__input'),
  backdropElt: document.querySelector('.backdrop'),
  modal: document.querySelector('#modal-window'),
  bodyElt: document.querySelector('body'),
  sentinel: document.querySelector('#sentinel'),
  libraryBtn: document.querySelector('#library-button'),
  // modalButtonWatched: document.querySelector('.modal-button__watched'),
  // modalButtonQueue: document.querySelector('.modal-button__queue'),
  headerBckgr: document.querySelector('.header__background'),
  headerSearchInputWrapper: document.querySelector('.search__input-wrapper'),
  watchedBtnLibrary: document.querySelector('.watched-button'),
  queueBtnLibrary: document.querySelector('.queue-button'),
  homeBtn: document.querySelector('#home-button'),
  libraryBtn: document.querySelector('#library-button'),
  searchForm: document.querySelector('.search-form'),
  loadMoreBtn: document.querySelector('#loadMore'),
  loadMoreToSearchBtn: document.querySelector('#loadMoreToSearch'),
  logo: document.querySelector('.logo'),
  error: document.querySelector('.wrong-search'),
  darkFooterTheme: document.querySelector('.footer'),
};
export default refs;
